// Internal recommendation catalog for the Gift Finder.
// These are printable idea concepts, not the active storefront inventory.
// Each entry is meant to help a customer discover what Mitten Makes could make to order.

export const GIFT_FINDER_CATALOG = [
  {
    id: 'mini-articulated-dragon',
    name: 'Mini Articulated Dragon',
    shortDescription: 'A small flexy dragon idea with collectible energy and enough movement to feel fun in-hand.',
    whyItFits: 'It hits that dragon-and-fantasy lane without jumping straight to a big, higher-commitment print.',
    recipientTypes: ['kid', 'teen', 'friend'],
    ageRanges: ['6-8', '9-12', '13-17', '18-29'],
    occasions: ['birthday', 'holiday', 'just-because', 'desk-toy'],
    interests: ['dragons', 'fantasy', 'fidgets'],
    budgets: ['10-20'],
    tags: ['dragon', 'fantasy', 'articulated', 'giftable', 'fidget', 'desk-friendly'],
    badge: 'Gift Favorite',
    complexity: 'medium',
    customizationLevel: 'medium',
    imagePlaceholder: 'Dragon mini',
    internalCategory: 'articulated-dragons',
    submissionLabel: 'Mini articulated dragon idea'
  },
  {
    id: 'dragon-egg-desk-buddy',
    name: 'Dragon Egg Desk Buddy',
    shortDescription: 'A fantasy-themed egg or little dragon display idea that feels playful on a shelf or desk.',
    whyItFits: 'It works when someone likes dragons but wants something more display-friendly than a straight fidget.',
    recipientTypes: ['kid', 'teen', 'adult', 'friend'],
    ageRanges: ['6-8', '9-12', '13-17', '18-29', '30-49'],
    occasions: ['birthday', 'holiday', 'desk-toy', 'custom-gift'],
    interests: ['dragons', 'fantasy', 'cute-decor'],
    budgets: ['10-20', '20-35'],
    tags: ['dragon', 'fantasy', 'desk-friendly', 'decor', 'custom-friendly'],
    badge: 'Desk-Friendly',
    complexity: 'medium',
    customizationLevel: 'medium',
    imagePlaceholder: 'Egg display',
    internalCategory: 'desk-toys',
    submissionLabel: 'Dragon egg desk buddy idea'
  },
  {
    id: 'pocket-dino-fidget',
    name: 'Pocket Dino Fidget',
    shortDescription: 'A small dinosaur-shaped fidget idea designed to be easy to toss in a pocket or backpack.',
    whyItFits: 'It gives dinosaur fans something tactile, giftable, and easy to carry around.',
    recipientTypes: ['kid', 'teen'],
    ageRanges: ['3-5', '6-8', '9-12', '13-17'],
    occasions: ['birthday', 'party-favor', 'classroom-prize', 'just-because'],
    interests: ['dinosaurs', 'fidgets', 'sensory-items'],
    budgets: ['under-10', '10-20'],
    tags: ['dino', 'fidget', 'sensory', 'small-gift', 'low-print-time', 'kid-friendly'],
    badge: 'Great for Kids',
    complexity: 'low',
    customizationLevel: 'low',
    imagePlaceholder: 'Dino fidget',
    internalCategory: 'fidget-toys',
    submissionLabel: 'Pocket dino fidget idea'
  },
  {
    id: 'mini-dino-keychain',
    name: 'Mini Dino Keychain',
    shortDescription: 'A little dinosaur keychain concept that can clip onto a backpack, lunchbox, or party bag.',
    whyItFits: 'It keeps the dinosaur theme simple, affordable, and easy to gift in quantity.',
    recipientTypes: ['kid', 'teen', 'friend'],
    ageRanges: ['3-5', '6-8', '9-12', '13-17'],
    occasions: ['birthday', 'party-favor', 'classroom-prize', 'holiday'],
    interests: ['dinosaurs', 'animals', 'personalized-items'],
    budgets: ['under-10', '10-20'],
    tags: ['dino', 'keychain', 'small-gift', 'low-print-time', 'bag-friendly'],
    badge: 'Budget Pick',
    complexity: 'low',
    customizationLevel: 'medium',
    imagePlaceholder: 'Dino clip',
    internalCategory: 'mini-keychain-fidgets',
    submissionLabel: 'Mini dino keychain idea'
  },
  {
    id: 'dino-bookmark',
    name: 'Dino Bookmark',
    shortDescription: 'A themed bookmark idea with a dinosaur silhouette, fossil pattern, or playful print-through cutout.',
    whyItFits: 'It is an easy gift add-on for kids who like reading, classroom bundles, or small themed extras.',
    recipientTypes: ['kid', 'teacher', 'friend'],
    ageRanges: ['6-8', '9-12', '13-17'],
    occasions: ['birthday', 'thank-you', 'classroom-prize', 'holiday'],
    interests: ['dinosaurs', 'books-reading'],
    budgets: ['under-10'],
    tags: ['dino', 'bookmark', 'small-gift', 'low-print-time', 'classroom-friendly'],
    badge: 'Budget Pick',
    complexity: 'low',
    customizationLevel: 'low',
    imagePlaceholder: 'Dino bookmark',
    internalCategory: 'bookmarks',
    submissionLabel: 'Dino bookmark idea'
  },
  {
    id: 'dino-desk-buddy',
    name: 'Dino Desk Buddy',
    shortDescription: 'A small desktop creature idea with a dinosaur vibe that feels more collectible than toy-store generic.',
    whyItFits: 'It turns the dinosaur theme into something displayable and gift-ready for desks, shelves, or reading nooks.',
    recipientTypes: ['kid', 'teen', 'friend'],
    ageRanges: ['6-8', '9-12', '13-17', '18-29'],
    occasions: ['birthday', 'desk-toy', 'custom-gift', 'just-because'],
    interests: ['dinosaurs', 'cute-decor', 'desk-accessories'],
    budgets: ['10-20', '20-35'],
    tags: ['dino', 'desk-friendly', 'decor', 'custom-friendly'],
    badge: 'Gift Favorite',
    complexity: 'medium',
    customizationLevel: 'medium',
    imagePlaceholder: 'Dino buddy',
    internalCategory: 'desk-toys',
    submissionLabel: 'Dino desk buddy idea'
  },
  {
    id: 'flexi-animal-keychain',
    name: 'Flexi Animal Keychain',
    shortDescription: 'A bendy animal keychain idea with a little movement and a playful clip-on feel.',
    whyItFits: 'It is one of the easiest crowd-pleasers when someone wants animals, something small, or a lower budget.',
    recipientTypes: ['kid', 'teen', 'friend', 'parent'],
    ageRanges: ['3-5', '6-8', '9-12', '13-17', '18-29'],
    occasions: ['birthday', 'party-favor', 'classroom-prize', 'just-because', 'holiday'],
    interests: ['animals', 'fidgets', 'sensory-items'],
    budgets: ['under-10', '10-20'],
    tags: ['animal', 'keychain', 'small-gift', 'flexi', 'low-print-time', 'fidget'],
    badge: 'Great for Kids',
    complexity: 'low',
    customizationLevel: 'medium',
    imagePlaceholder: 'Animal clip',
    internalCategory: 'mini-keychain-fidgets',
    submissionLabel: 'Flexi animal keychain idea'
  },
  {
    id: 'sensory-fidget-clicker',
    name: 'Sensory Fidget Clicker',
    shortDescription: 'A simple clicky fidget idea built for repetitive motion, satisfying sound, and one-handed use.',
    whyItFits: 'It is a strong match when someone wants sensory support, a desk fidget, or a small everyday carry piece.',
    recipientTypes: ['kid', 'teen', 'adult', 'coworker', 'friend'],
    ageRanges: ['6-8', '9-12', '13-17', '18-29', '30-49', '50+'],
    occasions: ['birthday', 'desk-toy', 'just-because', 'party-favor'],
    interests: ['fidgets', 'sensory-items', 'desk-accessories'],
    budgets: ['under-10', '10-20'],
    tags: ['fidget', 'sensory', 'clicker', 'desk-friendly', 'small-gift', 'low-print-time'],
    badge: 'Budget Pick',
    complexity: 'low',
    customizationLevel: 'low',
    imagePlaceholder: 'Clicker',
    internalCategory: 'fidget-toys',
    submissionLabel: 'Sensory fidget clicker idea'
  },
  {
    id: 'infinity-cube-desk-fidget',
    name: 'Infinity Cube Desk Fidget',
    shortDescription: 'A fold-and-flip desk fidget idea that feels clean, modern, and easy to keep nearby.',
    whyItFits: 'It works especially well for older kids, teens, adults, and anyone who wants a more low-key desk toy.',
    recipientTypes: ['teen', 'adult', 'coworker', 'friend', 'teacher'],
    ageRanges: ['9-12', '13-17', '18-29', '30-49', '50+'],
    occasions: ['desk-toy', 'birthday', 'thank-you', 'just-because'],
    interests: ['fidgets', 'sensory-items', 'desk-accessories', 'office-workspace'],
    budgets: ['10-20'],
    tags: ['fidget', 'desk-friendly', 'office', 'modern', 'sensory'],
    badge: 'Desk-Friendly',
    complexity: 'medium',
    customizationLevel: 'low',
    imagePlaceholder: 'Desk cube',
    internalCategory: 'desk-toys',
    submissionLabel: 'Infinity cube desk fidget idea'
  },
  {
    id: 'cute-desk-buddy-creature',
    name: 'Cute Desk Buddy Creature',
    shortDescription: 'A tiny creature idea meant to sit on a shelf, monitor stand, or desk as a cheerful little companion.',
    whyItFits: 'It is a nice in-between option when someone likes cute decor but still wants something playful and printable.',
    recipientTypes: ['kid', 'teen', 'adult', 'friend', 'coworker'],
    ageRanges: ['6-8', '9-12', '13-17', '18-29', '30-49'],
    occasions: ['birthday', 'desk-toy', 'just-because', 'holiday'],
    interests: ['animals', 'cute-decor', 'desk-accessories', 'fantasy'],
    budgets: ['10-20', '20-35'],
    tags: ['desk-friendly', 'cute', 'creature', 'decor'],
    badge: 'Gift Favorite',
    complexity: 'medium',
    customizationLevel: 'medium',
    imagePlaceholder: 'Desk buddy',
    internalCategory: 'desk-toys',
    submissionLabel: 'Cute desk buddy creature idea'
  },
  {
    id: 'personalized-name-keychain',
    name: 'Personalized Name Keychain',
    shortDescription: 'A custom keychain idea with a name, nickname, or short word worked into the print.',
    whyItFits: 'It is one of the easiest personalized gifts to make feel thoughtful without pushing the budget too high.',
    recipientTypes: ['kid', 'teen', 'adult', 'parent', 'friend'],
    ageRanges: ['6-8', '9-12', '13-17', '18-29', '30-49', '50+'],
    occasions: ['birthday', 'holiday', 'thank-you', 'custom-gift', 'just-because'],
    interests: ['personalized-items'],
    budgets: ['under-10', '10-20'],
    tags: ['personalized', 'keychain', 'custom-friendly', 'small-gift', 'bag-friendly'],
    badge: 'Personalized Pick',
    complexity: 'low',
    customizationLevel: 'high',
    imagePlaceholder: 'Name tag',
    internalCategory: 'personalized-keychains',
    submissionLabel: 'Personalized name keychain idea'
  },
  {
    id: 'custom-initial-key-tag',
    name: 'Custom Initial Key Tag',
    shortDescription: 'A small custom key tag idea built around initials, monograms, or short phrases.',
    whyItFits: 'It keeps personalization simple and polished, especially for party bags, teacher thank-yous, or little add-on gifts.',
    recipientTypes: ['teen', 'adult', 'teacher', 'coworker', 'friend'],
    ageRanges: ['9-12', '13-17', '18-29', '30-49', '50+'],
    occasions: ['thank-you', 'birthday', 'holiday', 'party-favor', 'custom-gift'],
    interests: ['personalized-items', 'sports', 'office-workspace'],
    budgets: ['under-10', '10-20'],
    tags: ['personalized', 'keychain', 'custom-friendly', 'small-gift', 'low-print-time'],
    badge: 'Personalized Pick',
    complexity: 'low',
    customizationLevel: 'high',
    imagePlaceholder: 'Initial tag',
    internalCategory: 'personalized-keychains',
    submissionLabel: 'Custom initial key tag idea'
  },
  {
    id: 'teacher-desk-name-plate',
    name: 'Teacher Desk Name Plate',
    shortDescription: 'A cheerful desk name plate idea for a classroom desk, reading table, or teacher workspace.',
    whyItFits: 'It lands well as a thank-you gift because it feels personal, useful, and classroom-ready at the same time.',
    recipientTypes: ['teacher', 'adult', 'coworker'],
    ageRanges: ['18-29', '30-49', '50+'],
    occasions: ['thank-you', 'holiday', 'custom-gift', 'desk-toy'],
    interests: ['desk-accessories', 'office-workspace', 'personalized-items'],
    budgets: ['20-35', '35-plus'],
    tags: ['teacher', 'desk', 'personalized', 'name-plate', 'office', 'custom-friendly'],
    badge: 'Desk-Friendly',
    complexity: 'medium',
    customizationLevel: 'high',
    imagePlaceholder: 'Desk name',
    internalCategory: 'desk-name-plates',
    submissionLabel: 'Teacher desk name plate idea'
  },
  {
    id: 'personalized-kids-name-sign',
    name: 'Personalized Kids Name Sign',
    shortDescription: 'A custom room sign idea with a child’s name, colors, or theme built into the print.',
    whyItFits: 'It works best when the gift needs to feel more personal and room-specific than a standard toy or shelf piece.',
    recipientTypes: ['kid', 'parent'],
    ageRanges: ['3-5', '6-8', '9-12'],
    occasions: ['birthday', 'holiday', 'custom-gift'],
    interests: ['personalized-items', 'cute-decor', 'fantasy'],
    budgets: ['20-35', '35-plus'],
    tags: ['personalized', 'name-sign', 'custom-friendly', 'room-decor'],
    badge: 'Personalized Pick',
    complexity: 'medium',
    customizationLevel: 'high',
    imagePlaceholder: 'Name sign',
    internalCategory: 'name-signs',
    submissionLabel: 'Personalized kids name sign idea'
  },
  {
    id: 'fantasy-themed-bookmark',
    name: 'Fantasy-Themed Bookmark',
    shortDescription: 'A bookmark idea with dragons, castles, stars, runes, or other fantasy-inspired details.',
    whyItFits: 'It is a strong low-commitment gift when someone likes books and fantasy more than clutter.',
    recipientTypes: ['kid', 'teen', 'adult', 'friend', 'teacher'],
    ageRanges: ['6-8', '9-12', '13-17', '18-29', '30-49', '50+'],
    occasions: ['birthday', 'holiday', 'thank-you', 'just-because', 'classroom-prize'],
    interests: ['fantasy', 'dragons', 'books-reading'],
    budgets: ['under-10'],
    tags: ['bookmark', 'fantasy', 'dragon', 'small-gift', 'low-print-time'],
    badge: 'Budget Pick',
    complexity: 'low',
    customizationLevel: 'medium',
    imagePlaceholder: 'Fantasy mark',
    internalCategory: 'bookmarks',
    submissionLabel: 'Fantasy-themed bookmark idea'
  },
  {
    id: 'animal-bookmark',
    name: 'Animal Bookmark',
    shortDescription: 'A playful bookmark idea featuring animal shapes, patterns, or a favorite creature theme.',
    whyItFits: 'It is easy to personalize around favorite animals and still keep the gift simple and affordable.',
    recipientTypes: ['kid', 'teacher', 'friend', 'parent'],
    ageRanges: ['6-8', '9-12', '13-17', '18-29', '30-49'],
    occasions: ['thank-you', 'birthday', 'classroom-prize', 'holiday'],
    interests: ['animals', 'books-reading'],
    budgets: ['under-10'],
    tags: ['bookmark', 'animal', 'small-gift', 'classroom-friendly', 'low-print-time'],
    badge: 'Great for Kids',
    complexity: 'low',
    customizationLevel: 'medium',
    imagePlaceholder: 'Animal mark',
    internalCategory: 'bookmarks',
    submissionLabel: 'Animal bookmark idea'
  },
  {
    id: 'photo-lithophane-gift',
    name: 'Photo Lithophane Gift',
    shortDescription: 'A custom photo lithophane idea that reveals the image beautifully when backlit or displayed near light.',
    whyItFits: 'It is one of the most sentimental made-to-order print ideas for family gifts, memorial pieces, and custom keepsakes.',
    recipientTypes: ['adult', 'parent', 'teacher', 'friend'],
    ageRanges: ['18-29', '30-49', '50+'],
    occasions: ['holiday', 'thank-you', 'custom-gift', 'birthday'],
    interests: ['personalized-items', 'cute-decor'],
    budgets: ['20-35', '35-plus'],
    tags: ['photo-gift', 'lithophane', 'custom-friendly', 'personalized', 'sentimental'],
    badge: 'Custom-Friendly',
    complexity: 'high',
    customizationLevel: 'high',
    imagePlaceholder: 'Photo glow',
    internalCategory: 'photo-lithophanes',
    submissionLabel: 'Photo lithophane gift idea'
  },
  {
    id: 'lit-photo-nightlight-insert',
    name: 'Lit Photo Nightlight Insert',
    shortDescription: 'A light-friendly photo insert idea that turns a favorite picture into a glowing keepsake display.',
    whyItFits: 'It feels especially strong for parents, grandparents, and custom gifts where the photo matters more than the shape itself.',
    recipientTypes: ['adult', 'parent', 'friend'],
    ageRanges: ['18-29', '30-49', '50+'],
    occasions: ['holiday', 'custom-gift', 'birthday', 'thank-you'],
    interests: ['personalized-items', 'cute-decor'],
    budgets: ['35-plus'],
    tags: ['photo-gift', 'nightlight', 'custom-friendly', 'personalized', 'lithophane'],
    badge: 'Custom-Friendly',
    complexity: 'high',
    customizationLevel: 'high',
    imagePlaceholder: 'Photo light',
    internalCategory: 'photo-lithophanes',
    submissionLabel: 'Lit photo nightlight insert idea'
  },
  {
    id: 'modular-pencil-cup-organizer',
    name: 'Modular Pencil Cup Organizer',
    shortDescription: 'A practical desk organizer idea with room for pencils, markers, scissors, or little tools.',
    whyItFits: 'It is useful enough for teachers and coworkers while still feeling more personal than a generic office supply.',
    recipientTypes: ['teacher', 'coworker', 'adult', 'parent'],
    ageRanges: ['18-29', '30-49', '50+'],
    occasions: ['thank-you', 'desk-toy', 'holiday', 'custom-gift'],
    interests: ['desk-accessories', 'office-workspace'],
    budgets: ['20-35', '35-plus'],
    tags: ['desk', 'organizer', 'teacher', 'office', 'custom-friendly'],
    badge: 'Desk-Friendly',
    complexity: 'medium',
    customizationLevel: 'medium',
    imagePlaceholder: 'Pencil cup',
    internalCategory: 'modular-desk-organizers',
    submissionLabel: 'Modular pencil cup organizer idea'
  },
  {
    id: 'desktop-catchall-tray',
    name: 'Desktop Catchall Tray',
    shortDescription: 'A low-profile tray idea for keys, earbuds, paperclips, jewelry, or other everyday little things.',
    whyItFits: 'It works for adults, coworkers, and parents because it feels useful right away without being too serious.',
    recipientTypes: ['adult', 'parent', 'coworker', 'friend'],
    ageRanges: ['18-29', '30-49', '50+'],
    occasions: ['thank-you', 'desk-toy', 'holiday', 'just-because'],
    interests: ['desk-accessories', 'office-workspace', 'cute-decor'],
    budgets: ['10-20', '20-35'],
    tags: ['desk', 'tray', 'office', 'decor'],
    badge: 'Desk-Friendly',
    complexity: 'low',
    customizationLevel: 'medium',
    imagePlaceholder: 'Catchall',
    internalCategory: 'custom-organizer-concepts',
    submissionLabel: 'Desktop catchall tray idea'
  },
  {
    id: 'gamer-desk-accessory',
    name: 'Gamer Desk Accessory',
    shortDescription: 'A themed desk piece idea for controllers, headphones, cable routing, or a gamer-tag display.',
    whyItFits: 'It gives video game fans something more personalized and useful than a generic trinket.',
    recipientTypes: ['teen', 'adult', 'friend', 'coworker'],
    ageRanges: ['13-17', '18-29', '30-49'],
    occasions: ['birthday', 'desk-toy', 'holiday', 'custom-gift'],
    interests: ['video-games', 'desk-accessories', 'office-workspace'],
    budgets: ['20-35', '35-plus'],
    tags: ['gamer', 'desk', 'custom-friendly', 'office', 'display'],
    badge: 'Desk-Friendly',
    complexity: 'medium',
    customizationLevel: 'high',
    imagePlaceholder: 'Gamer desk',
    internalCategory: 'desk-accessories',
    submissionLabel: 'Gamer desk accessory idea'
  },
  {
    id: 'sports-themed-keychain',
    name: 'Sports-Themed Keychain',
    shortDescription: 'A custom keychain idea with team colors, ball shapes, jersey numbers, or sports-inspired details.',
    whyItFits: 'It is easy to personalize around a favorite sport without turning the gift into a big custom project.',
    recipientTypes: ['kid', 'teen', 'adult', 'parent', 'friend'],
    ageRanges: ['6-8', '9-12', '13-17', '18-29', '30-49', '50+'],
    occasions: ['birthday', 'party-favor', 'holiday', 'just-because'],
    interests: ['sports', 'personalized-items'],
    budgets: ['under-10', '10-20'],
    tags: ['sports', 'keychain', 'small-gift', 'custom-friendly', 'low-print-time'],
    badge: 'Budget Pick',
    complexity: 'low',
    customizationLevel: 'high',
    imagePlaceholder: 'Sports tag',
    internalCategory: 'personalized-keychains',
    submissionLabel: 'Sports-themed keychain idea'
  },
  {
    id: 'party-favor-mini-fidget-set',
    name: 'Party Favor Mini Fidget Set',
    shortDescription: 'A small mixed set idea with mini clickers, bendy pieces, or little fidgets sized for party bags.',
    whyItFits: 'It is one of the strongest fits when you need a lot of little gifts that still feel fun and printable.',
    recipientTypes: ['kid', 'teen', 'parent', 'teacher'],
    ageRanges: ['3-5', '6-8', '9-12', '13-17'],
    occasions: ['party-favor', 'birthday', 'classroom-prize'],
    interests: ['fidgets', 'sensory-items'],
    budgets: ['under-10', '10-20'],
    tags: ['bundle-friendly', 'fidget', 'sensory', 'party', 'low-print-time', 'mini'],
    badge: 'Party Bundle',
    complexity: 'low',
    customizationLevel: 'medium',
    imagePlaceholder: 'Mini set',
    internalCategory: 'party-favor-bundles',
    submissionLabel: 'Party favor mini fidget set idea'
  },
  {
    id: 'classroom-reward-token-set',
    name: 'Classroom Reward Token Set',
    shortDescription: 'A token or reward-marker set idea for teachers, reading charts, or classroom milestones.',
    whyItFits: 'It is practical for classroom use and easy to theme around reading, behavior goals, or a school subject.',
    recipientTypes: ['teacher', 'kid', 'parent'],
    ageRanges: ['3-5', '6-8', '9-12'],
    occasions: ['classroom-prize', 'thank-you', 'custom-gift'],
    interests: ['books-reading', 'personalized-items', 'desk-accessories'],
    budgets: ['10-20', '20-35'],
    tags: ['bundle-friendly', 'classroom', 'teacher', 'tokens', 'custom-friendly'],
    badge: 'Party Bundle',
    complexity: 'medium',
    customizationLevel: 'high',
    imagePlaceholder: 'Reward set',
    internalCategory: 'classroom-prize-bundles',
    submissionLabel: 'Classroom reward token set idea'
  },
  {
    id: 'custom-shelf-name-display',
    name: 'Custom Shelf Name Display',
    shortDescription: 'A freestanding display idea with a name or short phrase designed for shelves, desks, or photo nooks.',
    whyItFits: 'It is a good middle ground between a sign and a decor piece when you want a name-forward gift.',
    recipientTypes: ['kid', 'teen', 'adult', 'parent', 'friend'],
    ageRanges: ['6-8', '9-12', '13-17', '18-29', '30-49', '50+'],
    occasions: ['birthday', 'holiday', 'custom-gift', 'just-because'],
    interests: ['personalized-items', 'cute-decor', 'desk-accessories'],
    budgets: ['20-35', '35-plus'],
    tags: ['personalized', 'shelf-display', 'name-sign', 'custom-friendly', 'decor'],
    badge: 'Personalized Pick',
    complexity: 'medium',
    customizationLevel: 'high',
    imagePlaceholder: 'Shelf name',
    internalCategory: 'custom-display-decor',
    submissionLabel: 'Custom shelf name display idea'
  },
  {
    id: 'desk-decor-creature-set',
    name: 'Desk Decor Creature Set',
    shortDescription: 'A small creature set idea meant for monitor stands, bookshelves, or playful desk corners.',
    whyItFits: 'It works well when the gift should feel cute and displayable instead of purely practical.',
    recipientTypes: ['teen', 'adult', 'coworker', 'friend'],
    ageRanges: ['9-12', '13-17', '18-29', '30-49'],
    occasions: ['desk-toy', 'birthday', 'holiday', 'just-because'],
    interests: ['cute-decor', 'animals', 'fantasy', 'desk-accessories'],
    budgets: ['20-35'],
    tags: ['desk-friendly', 'decor', 'creature', 'bundle-friendly'],
    badge: 'Gift Favorite',
    complexity: 'medium',
    customizationLevel: 'medium',
    imagePlaceholder: 'Creature set',
    internalCategory: 'custom-display-decor',
    submissionLabel: 'Desk decor creature set idea'
  },
  {
    id: 'personalized-bag-tag',
    name: 'Personalized Bag Tag',
    shortDescription: 'A bag tag idea with a name, icon, sport, or theme that makes backpacks and totes easier to spot.',
    whyItFits: 'It is especially good for school, sports, travel, and gifts that need personalization without a huge budget.',
    recipientTypes: ['kid', 'teen', 'adult', 'parent', 'friend'],
    ageRanges: ['3-5', '6-8', '9-12', '13-17', '18-29', '30-49'],
    occasions: ['birthday', 'holiday', 'party-favor', 'custom-gift'],
    interests: ['personalized-items', 'sports', 'animals', 'video-games'],
    budgets: ['under-10', '10-20'],
    tags: ['personalized', 'bag-tag', 'small-gift', 'custom-friendly', 'bag-friendly'],
    badge: 'Personalized Pick',
    complexity: 'low',
    customizationLevel: 'high',
    imagePlaceholder: 'Bag tag',
    internalCategory: 'personalized-keychains',
    submissionLabel: 'Personalized bag tag idea'
  },
  {
    id: 'simple-custom-door-sign',
    name: 'Simple Custom Door Sign',
    shortDescription: 'A clean room, office, or classroom sign idea with a name, title, or short phrase.',
    whyItFits: 'It is one of the easiest custom decor concepts to tailor to a person, room, or workspace.',
    recipientTypes: ['kid', 'adult', 'teacher', 'coworker', 'parent'],
    ageRanges: ['6-8', '9-12', '13-17', '18-29', '30-49', '50+'],
    occasions: ['custom-gift', 'holiday', 'thank-you', 'birthday'],
    interests: ['personalized-items', 'desk-accessories', 'cute-decor', 'office-workspace'],
    budgets: ['20-35', '35-plus'],
    tags: ['personalized', 'door-sign', 'name-sign', 'custom-friendly', 'office'],
    badge: 'Custom-Friendly',
    complexity: 'medium',
    customizationLevel: 'high',
    imagePlaceholder: 'Door sign',
    internalCategory: 'name-signs',
    submissionLabel: 'Simple custom door sign idea'
  },
  {
    id: 'mini-creature-prize-bundle',
    name: 'Mini Creature Prize Bundle',
    shortDescription: 'A classroom or party bundle idea built around tiny creatures, little critters, or themed minis.',
    whyItFits: 'It gives you the “lots of small wins” feel that works well for prize boxes, team handouts, and party extras.',
    recipientTypes: ['kid', 'teacher', 'parent'],
    ageRanges: ['3-5', '6-8', '9-12'],
    occasions: ['party-favor', 'classroom-prize', 'birthday'],
    interests: ['animals', 'cute-decor', 'fidgets'],
    budgets: ['10-20', '20-35'],
    tags: ['bundle-friendly', 'animal', 'mini', 'classroom', 'party'],
    badge: 'Party Bundle',
    complexity: 'medium',
    customizationLevel: 'medium',
    imagePlaceholder: 'Mini bundle',
    internalCategory: 'party-favor-bundles',
    submissionLabel: 'Mini creature prize bundle idea'
  },
  {
    id: 'office-cable-buddy',
    name: 'Office Cable Buddy',
    shortDescription: 'A friendly cable helper idea that keeps a charging cord or desk cable from sliding out of reach.',
    whyItFits: 'It gives desk and workspace shoppers something practical that still feels fun and giftable.',
    recipientTypes: ['adult', 'coworker', 'teacher', 'friend'],
    ageRanges: ['18-29', '30-49', '50+'],
    occasions: ['desk-toy', 'thank-you', 'holiday', 'just-because'],
    interests: ['desk-accessories', 'office-workspace', 'cute-decor'],
    budgets: ['10-20', '20-35'],
    tags: ['desk', 'organizer', 'office', 'desk-friendly', 'custom-friendly'],
    badge: 'Desk-Friendly',
    complexity: 'medium',
    customizationLevel: 'medium',
    imagePlaceholder: 'Cable helper',
    internalCategory: 'custom-organizer-concepts',
    submissionLabel: 'Office cable buddy idea'
  },
  {
    id: 'funny-desk-decor-creature',
    name: 'Funny Desk Decor Creature',
    shortDescription: 'A silly desk creature idea that feels like a tiny conversation piece for a home office or coworker gift.',
    whyItFits: 'It is a strong fit when you want something lighthearted for a desk without making it fully practical.',
    recipientTypes: ['adult', 'coworker', 'friend', 'teacher'],
    ageRanges: ['18-29', '30-49', '50+'],
    occasions: ['desk-toy', 'thank-you', 'just-because', 'holiday'],
    interests: ['cute-decor', 'desk-accessories', 'office-workspace', 'animals'],
    budgets: ['10-20', '20-35'],
    tags: ['desk-friendly', 'creature', 'decor', 'office', 'funny'],
    badge: 'Desk-Friendly',
    complexity: 'medium',
    customizationLevel: 'medium',
    imagePlaceholder: 'Desk creature',
    internalCategory: 'custom-display-decor',
    submissionLabel: 'Funny desk decor creature idea'
  },
  {
    id: 'classroom-bookmark-bundle',
    name: 'Classroom Bookmark Bundle',
    shortDescription: 'A themed bookmark bundle idea sized for reading prizes, welcome bags, or student rewards.',
    whyItFits: 'It is a clean option for teachers who want something lightweight, useful, and easy to hand out in multiples.',
    recipientTypes: ['teacher', 'kid', 'parent'],
    ageRanges: ['6-8', '9-12', '13-17'],
    occasions: ['classroom-prize', 'thank-you', 'party-favor'],
    interests: ['books-reading', 'animals', 'fantasy'],
    budgets: ['under-10', '10-20'],
    tags: ['bundle-friendly', 'bookmark', 'classroom', 'teacher', 'low-print-time'],
    badge: 'Party Bundle',
    complexity: 'low',
    customizationLevel: 'medium',
    imagePlaceholder: 'Bookmark set',
    internalCategory: 'classroom-prize-bundles',
    submissionLabel: 'Classroom bookmark bundle idea'
  },
  {
    id: 'sports-locker-bag-tag',
    name: 'Sports Locker Bag Tag',
    shortDescription: 'A sport-themed bag tag idea made for backpacks, duffels, or team gift extras.',
    whyItFits: 'It is a simple way to make the gift feel specific to a sport, team color, or player number.',
    recipientTypes: ['kid', 'teen', 'parent', 'friend'],
    ageRanges: ['6-8', '9-12', '13-17', '18-29'],
    occasions: ['birthday', 'party-favor', 'holiday', 'just-because'],
    interests: ['sports', 'personalized-items'],
    budgets: ['under-10', '10-20'],
    tags: ['sports', 'bag-tag', 'small-gift', 'custom-friendly', 'low-print-time'],
    badge: 'Budget Pick',
    complexity: 'low',
    customizationLevel: 'high',
    imagePlaceholder: 'Locker tag',
    internalCategory: 'personalized-keychains',
    submissionLabel: 'Sports locker bag tag idea'
  },
  {
    id: 'rocket-desk-buddy',
    name: 'Rocket Desk Buddy',
    shortDescription: 'A space-themed desk buddy idea with a rocket or astronaut feel that still works as a simple shelf gift.',
    whyItFits: 'It gives space and science fans something displayable and playful without needing a huge custom build.',
    recipientTypes: ['kid', 'teen', 'friend', 'coworker'],
    ageRanges: ['6-8', '9-12', '13-17', '18-29', '30-49'],
    occasions: ['birthday', 'desk-toy', 'holiday', 'just-because'],
    interests: ['space-science', 'desk-accessories', 'cute-decor'],
    budgets: ['10-20', '20-35'],
    tags: ['space', 'science', 'rocket', 'desk', 'desk-friendly', 'decor'],
    badge: 'Desk-Friendly',
    complexity: 'medium',
    customizationLevel: 'medium',
    imagePlaceholder: 'Rocket buddy',
    internalCategory: 'desk-toys',
    submissionLabel: 'Rocket desk buddy idea'
  },
  {
    id: 'moon-phase-bookmark',
    name: 'Moon Phase Bookmark',
    shortDescription: 'A celestial bookmark idea with moon phases, stars, or clean night-sky pattern details.',
    whyItFits: 'It works especially well when someone likes space, reading, or gifts that feel a little more aesthetic.',
    recipientTypes: ['teen', 'adult', 'friend', 'teacher'],
    ageRanges: ['9-12', '13-17', '18-29', '30-49', '50+'],
    occasions: ['holiday', 'thank-you', 'just-because', 'birthday'],
    interests: ['space-science', 'books-reading', 'cute-decor'],
    budgets: ['under-10', '10-20'],
    tags: ['space', 'moon', 'bookmark', 'small-gift', 'low-print-time', 'design'],
    badge: 'Gift Favorite',
    complexity: 'low',
    customizationLevel: 'medium',
    imagePlaceholder: 'Moon bookmark',
    internalCategory: 'bookmarks',
    submissionLabel: 'Moon phase bookmark idea'
  },
  {
    id: 'science-token-mini-set',
    name: 'Science Token Mini Set',
    shortDescription: 'A small set idea with science-themed tokens, badges, or icons for rewards, handouts, or little extras.',
    whyItFits: 'It is a strong fit for classroom themes, science lovers, and small grouped gifts that still feel specific.',
    recipientTypes: ['kid', 'teacher', 'parent'],
    ageRanges: ['6-8', '9-12', '13-17'],
    occasions: ['classroom-prize', 'party-favor', 'thank-you'],
    interests: ['space-science', 'school-classroom', 'books-reading'],
    budgets: ['under-10', '10-20'],
    tags: ['science', 'classroom', 'tokens', 'bundle-friendly', 'low-print-time'],
    badge: 'Party Bundle',
    complexity: 'low',
    customizationLevel: 'medium',
    imagePlaceholder: 'Science set',
    internalCategory: 'classroom-prize-bundles',
    submissionLabel: 'Science token mini set idea'
  },
  {
    id: 'pet-name-bag-tag',
    name: 'Pet Name Bag Tag',
    shortDescription: 'A custom tag idea with a pet name, paw icon, or favorite animal silhouette for bags, crates, or keys.',
    whyItFits: 'It blends animals and personalization in a way that feels thoughtful without becoming a big custom project.',
    recipientTypes: ['kid', 'teen', 'adult', 'parent', 'friend'],
    ageRanges: ['6-8', '9-12', '13-17', '18-29', '30-49', '50+'],
    occasions: ['birthday', 'holiday', 'custom-gift', 'just-because'],
    interests: ['pets', 'animals', 'personalized-items', 'travel'],
    budgets: ['under-10', '10-20'],
    tags: ['pet', 'animal', 'bag-tag', 'personalized', 'custom-friendly', 'small-gift'],
    badge: 'Personalized Pick',
    complexity: 'low',
    customizationLevel: 'high',
    imagePlaceholder: 'Pet tag',
    internalCategory: 'personalized-keychains',
    submissionLabel: 'Pet name bag tag idea'
  },
  {
    id: 'music-note-bookmark',
    name: 'Music Note Bookmark',
    shortDescription: 'A slim bookmark idea with music notes, instruments, or band-inspired pattern details.',
    whyItFits: 'It gives music fans a cleaner small gift option when a keychain or desk item feels less personal.',
    recipientTypes: ['kid', 'teen', 'adult', 'teacher', 'friend'],
    ageRanges: ['6-8', '9-12', '13-17', '18-29', '30-49'],
    occasions: ['thank-you', 'birthday', 'holiday', 'classroom-prize'],
    interests: ['music', 'books-reading', 'art-design'],
    budgets: ['under-10'],
    tags: ['music', 'bookmark', 'small-gift', 'low-print-time', 'design'],
    badge: 'Budget Pick',
    complexity: 'low',
    customizationLevel: 'medium',
    imagePlaceholder: 'Music mark',
    internalCategory: 'bookmarks',
    submissionLabel: 'Music note bookmark idea'
  },
  {
    id: 'pattern-play-bookmark-set',
    name: 'Pattern Play Bookmark Set',
    shortDescription: 'A bookmark set idea built around geometric, abstract, or art-forward patterns for readers who like cleaner design.',
    whyItFits: 'It lands well for art and design interests when the gift should still be simple, useful, and easy to scan.',
    recipientTypes: ['teen', 'adult', 'teacher', 'coworker', 'friend'],
    ageRanges: ['13-17', '18-29', '30-49', '50+'],
    occasions: ['thank-you', 'holiday', 'just-because', 'birthday'],
    interests: ['art-design', 'books-reading', 'office-workspace'],
    budgets: ['under-10', '10-20'],
    tags: ['art', 'design', 'bookmark', 'low-print-time', 'small-gift'],
    badge: 'Gift Favorite',
    complexity: 'low',
    customizationLevel: 'medium',
    imagePlaceholder: 'Pattern marks',
    internalCategory: 'bookmarks',
    submissionLabel: 'Pattern play bookmark set idea'
  },
  {
    id: 'spooky-shelf-creature',
    name: 'Spooky Shelf Creature',
    shortDescription: 'A tiny spooky creature idea with goth, cryptid, or Halloween-adjacent energy for shelves and desks.',
    whyItFits: 'It gives spooky or goth-leaning gift ideas a more specific lane than generic cute decor.',
    recipientTypes: ['teen', 'adult', 'friend', 'coworker'],
    ageRanges: ['13-17', '18-29', '30-49', '50+'],
    occasions: ['birthday', 'holiday', 'desk-toy', 'just-because'],
    interests: ['spooky-goth', 'cute-decor', 'fantasy'],
    budgets: ['10-20', '20-35'],
    tags: ['spooky', 'goth', 'creature', 'desk-friendly', 'decor'],
    badge: 'Gift Favorite',
    complexity: 'medium',
    customizationLevel: 'medium',
    imagePlaceholder: 'Spooky creature',
    internalCategory: 'custom-display-decor',
    submissionLabel: 'Spooky shelf creature idea'
  }
];
